version: '3.7'

services:

  web:
    image: node:20-alpine
    restart: "no"
    env_file:
      - .env.example
      - .env
    volumes:
      - ./web:/project/web
    working_dir: /project/web
    ports:
      - ${WEB_HTTP_PORT_HOST}:8080
    command: [ sh, -c, "npm c set cache /tmp --global && tail -f /dev/null" ]

  app:
    image: python:3.12-slim
    restart: "no"
    env_file:
      - .env
    ports:
      - ${API_HTTP_PORT_HOST}:8000
    volumes:
      - ./app:/project/app
      - pip-data:/usr/local/lib/python3.12/site-packages/
      - cache-data:/root/.cache/whisper
    working_dir: /project/app
    command: [ sh, -c, "tail -f /dev/null" ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 24G

volumes:
  pip-data:
  cache-data: